name: Java CI with Maven

on:
  workflow_dispatch: 
    
jobs:
  build:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ '21' ]
    

    name: Build with JDK ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin' # Using Eclipse Temurin distribution
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml
